disabled_rules:
  - file_length
  - function_body_length

  - type_name
  - identifier_name
  - trailing_comma
  - function_parameter_count
  - nesting
  - type_body_length
  - cyclomatic_complexity
excluded:
  - MyLeaderboard/Source/API/Generated
