disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - nesting
  - type_body_length
  - cyclomatic_complexity
excluded:
  - MyLeaderboard/Source/API/Generated

trailing_comma:
  mandatory_comma: true