disabled_rules:
  - type_name
  - identifier_name
  - line_length
  - trailing_comma
  - function_parameter_count
  - nesting
  - type_body_length
  - cyclomatic_complexity
excluded:
  - MyLeaderboard/Source/API/Generated
