#!/bin/sh

mint run syrup generate \
    ./MyLeaderboardApi/Source/GraphQL \
    ./MyLeaderboardApi/Source/API \
    ./MyLeaderboardApi/Source/API \
    Swift \
    --project ./.syrupProject.yml \
    --schema ./.syrupSchema.yml
