#!/bin/sh

mint run syrup generate \
    ./MyLeaderboard/Source/API/GraphQL \
    ./MyLeaderboard/Source/API/Generated \
    ./MyLeaderboard/Source/API/Generated \
    Swift \
    --project ./.syrupProject.yml \
    --schema ./.syrupSchema.yml
